apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-nodeport
  namespace: ns-{{ .Values.env }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}-pod
  ports:
    - name: "http"
      protocol: TCP
      port: 9001
      targetPort: 9000
      nodePort: 32000