apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ns-{{ .Values.env }}
  name: pod-reader-role
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps", "secrets", "endpoints"]
    verbs: ["get", "watch", "list", "create"]