apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-rolebinding
  namespace: ns-{{ .Values.env }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader-role
subjects:
  - kind: ServiceAccount
    name: pod-reader-account
    namespace: ns-{{ .Values.env }}